# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_auto_20180126_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='work',
            new_name='works',
        ),
    ]
